config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/pool'

  #taging path
  get 'tags/:tag', to: 'apps#index', as: :tag
  #root
  root 'pages#index'
  resources :apps
  resources :userskills, only: [:create, :destroy]
  resources :commitments, only: [:create, :destroy]
  
  devise_for :users
  # Must go after more specific devise routes
  resources :users, only: [:show, :update]
  # get 'users/profile/:id', to: 'users#show', as: :user
  
  #omniauth
  get "auth/github/", to: "apps#index"
  match "auth/github/callback" => "users#github_data", :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :user
  has_many :commitments, :dependent => :destroy
  acts_as_taggable
  attachment :image
  before_save :downcase_fields

  def downcase_fields
  self.name.downcase!
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commitment.rb
class Commitment < ApplicationRecord
  belongs_to :user
  belongs_to :app 
  validates_uniqueness_of :user_id, :scope => :app_id
end

app/models/skill.rb
class Skill < ApplicationRecord

  has_many :userskills
  has_many :users, through: :userskills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userskills
  has_many :skills, through: :userskills
  has_many :commitments
  has_many :apps, through: :commitments
  attachment :image

end

app/models/userskill.rb
class Userskill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  validates :user, uniqueness: { scope: :skill }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    if params[:tag]
      @apps = App.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 15)
    elsif params[:search]
      @apps = App.where('name LIKE ?', "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 15)
    else
       @apps = App.paginate(:page => params[:page], :per_page => 15)
    end
  end

  def show
    @app = App.find(params[:id])
    if @app.repo?
    @response = HTTParty.get('https://api.github.com/repos/myztajay/'+@app.repo+'/commits'+ `client_id=#{ENV["GITHUB_ID"]}&client_secret=#{ENV["GITHUB_SECRET"]}`)
    end

    # if params[:link_title]
    #   @link=params[:link_title]
    # end
  end

  def new
    @app = App.new
  end

  def create
    @app = App.new(app_parameters)
    @app.user_id = current_user.id
    @app.save

    if @app.save
      redirect_to app_path(@app)
    else
      render 'new'
    end
  end

  def edit
    @app = App.find(params[:id])
  end

  def update
    @app = App.find(params[:id])
   if @app.update(app_parameters)
     redirect_to @app
   else
     render 'edit'
   end
  end

  def destroy
    @app = App.find(params[:id])
    @app.destroy
    redirect_to apps_path
  end


  private
  def app_parameters
    params.require(:app).permit(:name, :description, :requirements, :developers_needed, :tag_list,:image,:remove_image, :repo)
  end
end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  def create

    if(!current_user)
      redirect_to "/users/sign_in"
    else
    respond_to do |format|
      @commitment = Commitment.new(commitment_parameters)
      @commitment.user = current_user
      @commiter = @commitment.user.email
      if @commitment.save
        # flash...
        format.html {}
        format.js {}
      else
        flash[:error]="you fucked up"
        format.html {}
        format.js {}
      end
    end
    end
  end

  def destroy
  end

  private

  def commitment_parameters
    params.require(:commitment).permit(:app_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @apps = App.first(6)
    @pop_apps = App.first(3)
  end
  
  def pool
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:github_data]
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    @user.update(user_profile_params)
    redirect_to @user
  end

  def github_data
    x = {github_name: githubname = data["info"]["nickname"]}
    current_user.update(x)
    puts data
    redirect_to '/apps#index'
  end

  private
  def user_profile_params
    params.require(:user).permit(:image,:remove_image)
  end

  def data
    request.env['omniauth.auth']
  end
end

app/controllers/userskills_controller.rb
class UserskillsController < ApplicationController


  def create
    respond_to do |format|
      @userskill = Userskill.new(userskill_parameters)
      @userskill.user = current_user
      @skills = current_user.skills
      @skill = @userskill.skill.skill
      if @userskill.save
        # flash...
        format.html {}
        format.js {}
      else
        flash[:error]="you fucked up"
        format.html {}
        format.js {}
      end
    end


  end

  def destroy
  end

  private

  def userskill_parameters
    params.require(:userskill).permit(:skill_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/userskills_helper.rb
module UserskillsHelper
end

app/views/apps/_app.html.erb
  <% @amount = @app.commitments.count*100/@app.developers_needed*100/100 %>
  <% if @app.commitments.count*100/@app.developers_needed*100/100 > 100 %>
      <% @bar = 100 %>
    <% else %>
      <% @bar = @app.commitments.count*100/@app.developers_needed*100/100%>
   <% end %>
   
<div class="creator_container">

    <%=link_to user_path(@app.user) do %>
      <%= image_tag attachment_url(@app.user, :image, :fill, 100, 100, fallback: "default.jpg") %>
    <%end%>

<h4>By </h4>
<p>
  <%= link_to @app.user.email, user_path(@app.user.id) %>
</p>
</div>

<div class="title_container">
  <h1><%= @app.name.capitalize %> </h1><Br>
  <p class="headline">
  <%= @app.description %>
  </p>
</div>
<hr>
<div class="img_container">
  <%= image_tag attachment_url(@app, :image, :fill, 700, 380, fallback: "default-app.jpg") %>
</div>

<div class="app_details">
<div class="panel panel-default match-img">
<div class="panel-heading">
    <h1 class="panel-title"><%= link_to @app.name.capitalize, app_path(@app) %> </h1>
</div>
  <div class="panel-body">

<div>
  <% if user_signed_in? %>
    <% if @app.user_id === current_user.id %>
      <%= link_to "Edit this App", edit_app_path(@app) %>
      <%= link_to "Delete this App", app_path(@app), method: :delete, data: {confirm: "Are you sure?"}%>
    <% end %>
  <%end%>

  <h4>Requirements </h4><p>
    <%= @app.requirements %>
  </p>

  <h4>Developers Needed</h4><p>
     <%=@app.name.capitalize%> has <%=@app.commitments.count%> and needs <%=@app.developers_needed %>
    <div class="progress">
       <%if @amount > 100%>
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% else %>
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% end %>
  </div>
  <h4>Tags</h4>
    <%@app.tag_list.each do |x| %>
  <%= link_to x, tag_path(x) %>
    <%end%>
  </p>
</div>
</div></div></div>

<!-- <div class="mini_nav_container">
  <ul class="list-inline">
    <li><h4><%=link_to "Overview", app_path(@app, :link_title=>"overview"), remote:true %></h4></li>
    <li><h4><%=link_to "Commitments", app_path(@app, :link_title=>"commitments"), remote:true %></h4></li>
    <li><h4><%=link_to "Github", app_path(@app, :link_title=>"github"), remote:true %></h4></li>
    <li><h4><%=link_to "Comments", app_path(@app, :link_title=>"comments"), remote:true %></h4></li>
  </ul>
</div>
<div id="app_content">

</div> -->

app/views/apps/_apps.html.erb
<% @apps.each do |app| %>

  <% @amount = app.commitments.count*100/app.developers_needed*100/100 %>
  <% if app.commitments.count*100/app.developers_needed*100/100 > 100 %>
      <% @bar = 100 %>
    <% else %>
      <% @bar = app.commitments.count*100/app.developers_needed*100/100%>
  <% end %>
  
  <div class="single_app pop_up ">
      <%=link_to app_path(app) do %>
        <%= image_tag attachment_url(app, :image, :fill, 350, 200, fallback: 'default-app-small.jpg'), :class => "app-image" %>
    <%end%>
    <br>
    <strong><%=link_to app.name, app_path(app)%></strong><br>
    <%=link_to user_path(app.user) do %>
      <%= image_tag attachment_url(app.user, :image, :fill, 25, 25, fallback: "default-nav.jpg") %>
    <%end%>
    <p>
      by <%=link_to app.user.email, user_path(app.user), :class => "alt_a" %>
    </p>
    <p>
      <%= truncate(app.description , length: 100, omission: '...')%>
    </p>
    <div class="small-app-detail">
      <div class="progress">
        <%if @amount > 100%>
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% else %>
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% end %>
      </div>
      
      <div class="mini-app-detail">
        <span><%=app.developers_needed %> developer needed </span>
        <span><%= app.commitments.count*100/app.developers_needed*100/100%>%</span>
        <span><%= app.created_at.strftime("%b %-d, %Y")  %></li></span>
      </div>
    </div>
  </div>

<%end%>

app/views/apps/_form.html.erb
 
    <%= form_for @app, :html => {:class => "form-inline"} do |f| %>
      <div class=" new-form ">
          <div class='form-text-fields'>
          <%= f.text_field :name, placeholder: "Name", class: 'form-field', :required => true %><br>
          <%= f.text_field :requirements, placeholder: "Requirements", class: 'form-field', :required => true%><br>
          <%= f.text_field :description, placeholder: "Description", class: 'form-field', :required => true%><br>
    
          <% if @app.repo? %>
            <%= f.label :repo%><br>
            <%= f.text_field :repo%><br>
          <% end %>
    
          <%= f.text_field :tag_list, placeholder: "Tags seperated with commas", class: 'form-field', :required => true %><br>
          <div class='dev-needed'>
          <%= f.label :developers_needed%><br>
          <%= f.select :developers_needed ,options_for_select(1..15) %><br>
          </div>
          </div>
          <div class='form-image'>
          
          <%= image_tag attachment_url(@app, :image, :fill, 100, 100, fallback: "default-form-img.jpg") %>
          <br>
          <%= f.attachment_field :image, class: 'form-field' %>
          <div>
          <%= f.check_box :remove_image , class: 'check-box' %>
          <%= f.label :remove_image %><br>
          </div>
          </div>
          
          <%= f.submit  class: 'btn btn-primary create-btn rounded-circle' %>
       
        </div> 
    <%end%>

app/views/apps/_pop_apps.html.erb
<% @pop_apps.each do |app| %>

  <% @amount = app.commitments.count*100/app.developers_needed*100/100 %>
  <% if app.commitments.count*100/app.developers_needed*100/100 > 100 %>
      <% @bar = 100 %>
    <% else %>
      <% @bar = app.commitments.count*100/app.developers_needed*100/100%>
  <% end %>

  <div class="single_app pop_up ">
      <%=link_to app_path(app) do %>
        <%= image_tag attachment_url(app, :image, :fill, 350, 200, fallback: 'default-app-small.jpg'), :class => "app-image" %>
    <%end%>
    <br>
    <strong><%=link_to app.name, app_path(app)%></strong><br>
    <%=link_to user_path(app.user) do %>
      <%= image_tag attachment_url(app.user, :image, :fill, 25, 25, fallback: "default-nav.jpg") %>
    <%end%>
    <p>
      by <%=link_to app.user.email, user_path(app.user), :class => "alt_a" %>
    </p>
    <p>
      <%= truncate(app.description , length: 100, omission: '...')%>
    </p>
    <div class="small-app-detail">
      <div class="progress">
        <%if @amount > 100%>
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% else %>
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=@bar%>%">
          <%= @amount %>%
          <span class="sr-only">40% Complete (success)</span>
          </div>
        <% end %>
      </div>
      
      <div class="mini-app-detail">
        <span><%=app.developers_needed %> developer needed </span>
        <span><%= app.commitments.count*100/app.developers_needed*100/100%>%</span>
        <span><%= app.created_at.strftime("%b %-d, %Y")  %></li></span>
      </div>
    </div>
  </div>
  
<%end%>

app/views/apps/edit.html.erb
<div class="container new-app-container">
<%= render 'form' %>
</div>

app/views/apps/index.html.erb
<div class="app-container top_margin container">
    <% if @apps.length < 1 %>
            <div class='self-centered'>
                <h3> Derp! No results found.</h3>
            </div>
    <%else %>
        <%= render 'apps' %><br>
        <div class ="pagination"><%= will_paginate @apps %></div>
    <% end %>
</div>

app/views/apps/index.js.erb
$('#apps').append('<%= j render('./apps/app') %>').hide().fadeIn();

<% if @apps.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@apps) %>');
<% else %>

    $('#loader').removeClass('loader')
    $('.pagination').remove();


<% end %>

app/views/apps/new.html.erb
<div class="container new-app-container">
  
      <%= render 'form' %>

</div>

app/views/apps/show.html.erb
<!-- testing with javascript_includ -->

<div class="app-show-container container top-margin">
<%= render 'app' %>
<hr>


<div class="git-container">
  <h2>MOST RECENT COMMITS </h2>

<%if @app.repo? == false and current_user != @app.user or !current_user %>
   <h3>App Creator has not submit a repository</h3>
<% end %>

<%if current_user == @app.user and @app.repo? == false %>
 <p>
   linked your existing repo, if you have one here
 </p>
 <div class="tiny_container">
 <ol>
   <li> Link your github account <%= link_to "HERE", auth_github_path %></li>
   <li> Authorize AppSpark</li>
   <li> Add the name of your Repo below</li>
   <%= form_for @app, remote: true do |f| %>
     <%= f.label :repo, "Just The Repo Name"%>
    <%= f.text_field :repo%>
    <%= f.submit "submit", :class =>"btn btn-primary" %>
    <% end %>
 </ol>
  </div>
<%end%>

<%if @app.repo? %>
  <table class="table table-hover" id="mytable">
    <thead>
      <tr>
        <th> Date</th>
        <th> Message</th>
        <th> Github Handle</th>
      </tr>
    </thead>
    <tbody>
    <% @response.first(5).each do |x|%>

    <tr>
      <td><%= x["commit"]["author"]["date"] %></td>

      <td><%=x["commit"]["message"]%></td>

      <td><%= x["commit"]["author"]["name"] %></td>
    </tr>
    <%end%>
  </tbody>
  </table>
<%end %>

<%if @app.repo === "" %>
  <p>
    user has not posted a repo yet...
  </p>
<%end%>

</div>


<div class=" commiters-container">
  <%= render './commitments/commitments' %>
  <%= render './commitments/commitment_button' %>
</div>


</div>
<%= render './layouts/footer'%>

app/views/apps/show.js.erb
// $(function(){
//
//
// if('<%=@link%>' == "overview"){
//   $("#app_content").html(
//     "<div class=overview_container> <p><%= @app.description %><p></div><%=@link%>")
//   }
//
//   else if('<%=@link%>' == "commitments"){$("#app_content").html(
//     "<div class=overview_container><%=@app.commitments%>")
//   }
//   else if('<%=@link%>' == "github"){$("#app_content").html(
//     "<div class=overview_container> <%=@link%><div>")
//   }
//
//   else{$("#app_content").html(
//     "<%=@link%>")
//   }



})

app/views/apps/update.html.erb
<h1>Apps#update</h1>
<p>Find me in app/views/apps/update.html.erb</p>

app/views/commitments/_commitment_button.html.erb
<%= form_for Commitment.new, remote: true do |f| %>
<%= f.submit "Commit", :class =>"btn btn-primary btn-block" %>
<%= f.hidden_field :app_id, :value => params[:id]%>
<% end %>

app/views/commitments/_commitments.html.erb
 <h2> COMMITMENTS </h2>

<% if @app.commitments.length === 0 %>
    <p>No one has commited to this app. Be the first to put a ring on it.</p>
   
<% else %>
 <% @app.commitments.each do |x| %>
        <p>
            <%=link_to user_path(@app.user) do %>
            <%= image_tag attachment_url(x.user, :image, :fill, 50, 50, fallback: "default-commitments.jpg") %>
            <%end%>
            <%=link_to x.user.email, user_path(x.user.id), :class => "alt_a"%>
         </p>
    <% end %>    
<% end %>
 
 <div id="commitment_container">
 </div>

app/views/commitments/create.html.erb
<h1>Commitments#create</h1>
<p>Find me in app/views/commitments/create.html.erb</p>

app/views/commitments/create.js.erb
$(function(){

  $("#commitment_container").append(
    "<p><%=@commiter%></p>")
})

app/views/layouts/_footer.html.erb
  <footer class="s24-bar text-color-white">

    <!-- Put any utility content here, such as social icons -->
    <div class="s24-bar__utilities w-full bg-color-black  m-a-0">
      <div class="container">
        <div class="col-sm-8">
          <h4>AppSpark is about helping one another</h4>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<% if current_user %>
<%= render '/layouts/nav_user' %>
<%else %>
<%= render '/layouts/nav_guest' %>
<%end%>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'AppSpark', pages_index_path, class: "navbar-brand" %>
      <p class='mini-brand'>Alpha</p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', pages_index_path %></li>
        <li><%= link_to 'Sign Up',new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path%></li>

          </ul>
        </li>

      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
       -->

      <%= form_tag apps_path, :method => 'get', :class =>"form-group navbar-form navbar-left" do %>
      <%= text_field_tag :search,"", :class =>'form-control'  %>
      <%= submit_tag "Search", :class=>"btn btn-default"%>
      <%end%>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'AppSpark', pages_index_path, class: "navbar-brand" %>
      <p class='mini-brand'>Alpha</p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Pool', pages_pool_path %></li>
        <li><%= link_to 'Apps', apps_path %></li>
        <li class="dropdown profile-nav-img">
          <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag attachment_url(current_user, :image, :fill, 37, 37, fallback: "default-nav.jpg"), class: 'circle-circle' %>
         </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user)%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path,  method: :delete%></li>
          </ul>
        </li>
        <li>
          <%= link_to 'Create App', new_app_path, class: "btn btn-primary create-btn rounded-circle" %>
        </li>

      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
       -->
      <div class="input-group">
      <%= form_tag apps_path, :method => 'get', :class =>"form-group navbar-form navbar-left" do %>
      <%= text_field_tag :search,"", :class =>'form-control'  %>
      <%= button_tag "", :class=>"btn btn-default" do%>
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      <%end%>
      <%end%>
      </div>
 
    


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SparkApp</title>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <%= yield :javascript_includes %> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render './layouts/nav'%>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/pool.html.erb
<div class="app-container container">
    <% @users.each do |user| %>
       <div class ="single-user"> 
            <%=link_to user_path(user) do %>
              <%= image_tag attachment_url(user, :image, :fill, 200, 200, fallback: "default-profile.jpg") %>
            <%end%>
            <h5><%= user.email %></h5>
            <p>
                <%= truncate( " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis elit et magna imperdiet 
            feugiat. Aliquam a egestas lorem, id semper arcu. Maecenas rhoncus at nulla eu semper. Cras ornare egestas 
            finibus. Nullam semper facilisis lorem. Cras ante ipsum, tempor eget bibendum vel, semper eu turpis. Nullam 
            rutrum magna nulla, at dapibus est condimentum eget. Duis mollis nulla eu tortor dignissim efficitur. 
            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas molestie
            imperdiet mauris quis suscipit. Integer a nibh eget enim fringilla varius." , length: 100, omission: '...')%>
            </p>
            <div>
    
                <% user.skills.first(5).each do |skill| %>
                    <i class="devicon-<%= skill.skill.downcase%>-plain colored big-icon"></i>
                <% end %> 
      
            </div>
            
       </div>
       
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container profile-container">
  <div class="panel panel-default app_width">
    <div class="panel-heading">
        <h4 class="panel-title">
            <h4><%=truncate(@user.email, length: 20, omission: '...')%></h4>

        </h4>
    </div>
    <div class="panel-body">
      <%= image_tag attachment_url(@user, :image, :fill, 280, 280, fallback: "default-profile.jpg") %>
    <%if @user == current_user%>
      <%= form_for current_user do |f| %>
        <%= f.attachment_field :image%>
        <%= f.check_box :remove_image %>
        <%= f.label :remove_image %>
        <%= f.submit %>
      <%end%>
    <%end%>
    </div>
</div>

<div class="panel panel-default app_width">
  <div class="panel-heading">
      <h4 class="panel-title"></h4>
        <h4>Skills</h4>
  </div>
  <div class="panel-body">
    <% if current_user === @user %>
      <%= render "./userskills/dropdown" %>
    <% end %>
    <% @user.skills.each do |x| %>
    <h3><%=x.skill%></h3>
    <% end %>
    <div id="skills_container"></div>
  </div>
</div>

<div class="panel panel-default app_width">
    <div class="panel-heading">
        <h4 class="panel-title">
            <h4>Commitments</h4>
        </h4>
    </div>
    <div class="panel-body">
      <ul>

      <% @user.commitments.each do |x| %>
        <li> <%=link_to x.app.name, app_path(x.app_id) %></li>
        <%end %>
      </ul>
    </div>
</div>
</div>

app/views/userskills/_dropdown.html.erb
<%= form_for Userskill.new, remote: true do |f| %>

 <%= f.collection_select :skill_id, Skill.order(:skill),:id,:skill %>
 <%= f.submit 'Add Skill'%>

 <% end %>

app/views/userskills/create.html.erb
<h1>Userskills#create</h1>
<p>Find me in app/views/userskills/create.html.erb</p>

app/views/userskills/create.js.erb
$(function(){
 if($('#<%=@skill%>').length > 0){
  alert('<%=@userskill.user.email%> already has this skill')
 } else {

  $("#skills_container").append(
    "<h3 id='<%=@skill%>'><%=@skill%></h3>")
    }
})

app/views/userskills/destroy.html.erb
<h1>Userskills#destroy</h1>
<p>Find me in app/views/userskills/destroy.html.erb</p>